inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/QuotedSymbols:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FormatStringToken:
  EnforcedStyle: unannotated
