inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'test/activesupport6/**/*'
    - 'test/activesupport7/**/*'

Style/QuotedSymbols:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FormatStringToken:
  EnforcedStyle: unannotated
