name: Rubocop Check

on:
  push:
    branches:
      - develop
      - master
    paths:
      - ".rubocop*.yml"
      - ".github/workflows/rubocop.yml"
      - "**/*.rb"
      - "**/*.gemspec"
      - "**/*.gemfile"
      - "Gemfile"
  pull_request:
    paths:
      - ".rubocop*.yml"
      - ".github/workflows/rubocop.yml"
      - "**/*.rb"
      - "**/*.gemspec"
      - "**/*.gemfile"
      - "Gemfile"

jobs:
  formatting-check:
    name: Formatting Check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Set-up RuboCop Problem Matcher
        uses: r7kamura/rubocop-problem-matchers-action@v1

      - name: Run rubocop
        run: bundle exec rubocop
